### PR TITLE
content/resources.md: Add jury hints about problem format

### PR DESCRIPTION
**Pull request by mpsijm**
@verwoerd Feedback is welcome :smile: 

I mostly describe what can be found on the hints page, so people know where to look. I've also added the specific hint for Java `Scanner` to the "General tips", since I think that's the most important one :slightly_smiling_face:

### CODE REVIEW

**Comment by verwoerd** [comment]
I have expanded the text a bit more. It aims to supplement the text with some hints and tricks. Let me know what you Think.

**Comment by mpsijm** [comment]
Thanks for expanding the hints! I've done another pass, you can merge if you agree with the latest changes :smile:

**Comment by mpsijm** [comment]
By the way, what's your thought on changing the config to allow raw HTML tags, instead of adding shortcodes for them? https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032

**Comment by verwoerd** [comment]
> By the way, what's your thought on changing the config to allow raw HTML tags, instead of adding shortcodes for them? https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032

I actually tried this, but didn't get it to work. Since the shortcode was easier to find then the reason why it didn't work. I'm not against it, but this worked faster for me. :)

**Review by verwoerd — APPROVED** [review]

**Comment by mpsijm** [comment]
> I actually tried this, but didn't get it to work. The shortcode was easier to find then the reason why it didn't work. I'm not against it, but this worked faster for me. :)

Interesting, it immediately worked on my machine when I tried it :joy: Pushed the fix to `master` :slightly_smiling_face:

**Pull request merged**
