### PR TITLE
Add dockerfile and github workflow

### PR DESCRIPTION
**Pull request by robertdijk**
Copied from https://github.com/WISVCH/nwerc-2022

### CODE REVIEW

**Comment by verwoerd** [comment]
Just to be aware, if the archive is included, this will create enormous docker images.

**Comment by robertdijk** [comment]
Yep, good point, we'll first have to see with beheer

**Comment by robertdijk** [comment]
In this pr and #15 we have to deal with both the LFS storage limit, LFS bandwidth limit (which also gets used by github workflows) [source](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage#tracking-storage-and-bandwidth-use), github container image storage limit and Container registry bandwidth limit.

**Comment by mpsijm** [comment]
Superseded by #28

**Pull request closed without merging**
