### PR TITLE
Update workflow

### PR DESCRIPTION
**Pull request by verwoerd**
Replaces #13 since I can't edit the branch directly.

### CODE REVIEW

**Comment by verwoerd** [comment]
Should we ask someone from Beheer to check that this doesn't cause issues with size?

**Comment by JoepdeJong** [comment]
If I understand it correctly, the active CHipCie website and the archives will be placed in the same (large) image? Since the active CHipCie website is frequently updated throughout the years and the archives are only updated once a year or so, isn't it better to make an archive image and an image for the active site?

**Comment by verwoerd** [comment]
The archive is updated roughly around 10 times a year, per contest:
* once to update the date, location and website (`data/archive` folder)
* once to add the resources (`resources/archive` folder), this can happen in multiple steps but we try to do it in 1
* sometimes add a link to the photos (`data/archive` folder)
It can be done to split this up in two images, but I'm not sure if the menu can handle this.

What we can do is move the `resources/archive`  to a separate image and serve this from a different root, e.g. `commissies.ch.tudelft.nl/chipcie-archive/`. The build should be quite trivial because we just need to put resources in a root directory of a webserver. I think it should be possible with 2 workflows in 1 repository, making us able to still test the links when developing locally. 

The only 2 risks I see are:
* deployments out of sync, when the Hugo image is earlier deployed then the archive image, but that should be max 30 mins unless a workflow failed
* External sites linking to archive files being broken, this are mostly the websites from BAPC/NWERC from last few years and can be triaged through PR requests at those sites.

**Comment by JoepdeJong** [comment]
> * deployments out of sync, when the Hugo image is earlier deployed then the archive image, but that should be max 30 mins unless a workflow failed
If you update the archive first, then this is not a problem right?
> * External sites linking to archive files being broken, this are mostly the websites from BAPC/NWERC from last few years and can be triaged through PR requests at those sites.
Maybe you can add redirects to the archive?

Does this setup significantly improve the memory used during the build? Or does it not really make a change?

**Comment by verwoerd** [comment]
The problem is not the memory usage, but the bandwidth usage. The build is a bit slow, but that should be free. For LFS there is a limit by GitHub for downloading for 50GB. Downloading the LFS objects in the workflow does count to this number. I think separating the two parts won't address this issue.

**Comment by JoepdeJong** [comment]
> The problem is not the memory usage, but the bandwidth usage. The build is a bit slow, but that should be free. For LFS there is a limit by GitHub for downloading for 50GB. Downloading the LFS objects in the workflow does count to this number. I think separating the two parts won't address this issue.

I just discussed this with Robert. I think it is best to separate the Archive from this repo. Then the image of the archive can be updated only incidentally. 



> What we can do is move the `resources/archive` to a separate image and serve this from a different root, e.g. `commissies.ch.tudelft.nl/chipcie-archive/`

I think this can be easily resolved with a redirect. If we serve the archive on a separate path. 


FYI: I am working on migrating the committee server Rob to the cloud. All repo's have to be moved or migrated in the coming weeks/months. Chipcie is now one of the blocking projects.

**Comment by mpsijm** [comment]
> Then the image of the archive can be updated only incidentally.

If I may guess, I think that the "regular" part of the website is updated even less often than the "archive" part of the website.

Besides that, if the only reason for splitting up the images is for saving LFS bandwidth, I don't think it's worth the trouble to split up the image. Either way, there will be one huge Docker image that will be updated once in a while :stuck_out_tongue: 

And @verwoerd since the LFS bandwidth issue is fixed in 358f93142601e837f148ba1508d8655abadf1724, is there a reason for this PR to still be a draft?

**Pull request merged**
