### PR TITLE
Add archive files

### PR DESCRIPTION
**Pull request by verwoerd**
- [x] Double check LFS space is not an issue

### CODE REVIEW

**Comment by robertdijk** [comment]
Another option we could consider is uploading the archive to a google cloud storage bucket, and server the archive from there.
That would cost $0.026 per GB per Month https://cloud.google.com/storage/pricing#multi-regions (or even cheaper if we go for a cheaper option). Was something like that already considered?

**Comment by verwoerd** [comment]
I did ask about this, but haven't had any response on it. For now LFS seems to be fine.

**Comment by robertdijk** [comment]
I think the LFS storage will be fine, but I'm worried about the bandwidth limit, because every time this data is pulled, the bandwith decreases.

> - If you download a 500 MB file that's tracked with LFS, you'll use 500 MB of the repository owner's allotted bandwidth. If a collaborator pushes a change to the file and you pull the new version to your local repository, you'll use another 500 MB of bandwidth, bringing the total usage for these two downloads to 1 GB of bandwidth.
> - If GitHub Actions downloads a 500 MB file that is tracked with LFS, it will use 500 MB of the repository owner's allotted bandwidth.

I'm afraid when this happens to much, CH's limit is reached, and other commities can't build their site anymore.

And if we also want auto deployment to the Kubernetes (which I think we have to have soon, since beheer wants to get rid of their server in io), we do need the container to be build using the github workflow. This will then download the repo on every change, which will easily eat up the whole quota. (+ the container repository size and bandwith quota)

So we can try this for now, but I think it's not future proof.

About the google cloud bucket:
I have enough rights in the chipcie project in google cloud to make a bucket for the data, so if we want to do that, and CH and beheer think it's a good idea, we can look at the options and try some things out ourself.

**Comment by verwoerd** [comment]
I think the automation can be solved by how the docker container is build. By using caching in git workflow we can avoid having to redownload all lfs files every build. For example https://github.com/nschloe/action-cached-lfs-checkout can resolve this issue.

For the size of the docker image should be fine if we make it a public package since we don't get any billing [(source)](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages). We might do something smart by using using [`COPY --link`](https://docs.docker.com/engine/reference/builder/#copy---link) in the Dockerfile to have less reduplicate layers when doing for example security upgrades on the base debian image.

I agree if we don't do this smart we can break a lot of things, but if we do it smart this can be build future proof.

I have never worked with google cloud buckets. How easy is it to add files? Can this be done by 3rd parties? A complaint I have received many times in the past years, is that the problem set archive is hard for other cities to add content from their contests (like BAPC and NWERC). This is much easier now with git. If this can also be achieved with a google cloud bucket then I have no issues with using google cloud bucket(or something similar).

**Comment by robertdijk** [comment]
Oehh, https://github.com/nschloe/action-cached-lfs-checkout looks like a nice solution to the workflow problem.

Okay it seems like you have a good idea on how to do this smart, so i'd say go for it :).

I wasn't aware that a goal was to make the archive updateable by 3rd parties, and then indeed a google cloud bucket is not suited for this, as you need certain access to upload files.

**Review by robertdijk — APPROVED** [review]

**Pull request merged**
