### PR TITLE
Edit DAPC 2024 news post and close registration

### PR DESCRIPTION
**Pull request by maartenweyns**

### CODE REVIEW

**Comment by verwoerd** [comment]
LGTM

-------- Original Message --------

**Review by mpsijm — APPROVED** [review]
Good idea to link the runner form :smile:

**Comment by maartenweyns** [comment]
Ow, the link doesn't work. It treats it as a subpath on the CHipCie website.

**Comment by maartenweyns** [comment]
I fixed it in a push to main 🙈

**Comment by mpsijm** [comment]
Sounds good to me :stuck_out_tongue: Thanks for noticing and fixing it, I confirmed that it works now :smile:

**Pull request merged**
