### PR TITLE
Add schedule news post for DAPC 2023

### PR DESCRIPTION
**Pull request by verwoerd**

### CODE REVIEW

**Comment by mpsijm** [comment]
Last year, we had a post with the entire information email, including the schedule. Do we want to do that this year again as well?

**Comment by verwoerd** [comment]
yes once this available we add that as a post as well.

**Comment by mpsijm** [comment]
I kind of want to prevent a flood of news posts for every small thing. So I guess we could replace the simple schedule post with the information email post, once it is available?

**Comment by verwoerd** [comment]
i have had questions about the schedule already and it was green lit during the meeting, so why wait?

**Review by mpsijm — APPROVED** [review]

**Pull request merged**
